script: bash ./deploy.sh
language: php
php:
- 7.2
env:
  global:
  - GH_REF: github.com/UDOOboard/X86II-Docs.git
  - secure: Tmhgsv5rtaUiOOJ7toxWPdYq5lMqpGczD2u5XtNZatW6fwaURSgassx8625Vv/w876ya1cL9C1gzacwcvn9kQBTCKK+YFtdP6lFZHsvB6PhOdOrjoLQEeY7TrsjznnERxgahmqvqaf8CN5Cmg/QS3unVWY5Go9nS50QVpqMiqWhQTjDIT2zTvNjdrnBZqfFJkS28Ce6YkePn47a9RBmYRraUByubO0J2JAFUyXpz/rcwf3LjJpPmv685G4QsNveHqAWouPlMa0btdav0NerGaPv+gEwP41i5/6j2pZKYDD4nxKTtsMfstNChkMEixbDMDitwUpWlx67eIe6a9goLyW8n5GUnxh30dTY4uuP0vtlRh+3PN1LCTXoRhPxbkoFeweuCgJnFrNcILrHSF0odXlzpQJo1r8R9MLP2e/0t27cMk5M4ar2lvX8DsfOS1jjoch+FFH4TBeNVKSfV9JgJeS4wWDrc8CGwhv2fUhPIJWUxVIzjx0LDjwZFnpMKyYjuVHjRHbb87BN3oKED+PZnKoSSz2gOHvAWJJZjn4KVBd5z2Lv8Ch6FHYb4MqxW6/vV9tjFjLidlqUMgpQ86+iq6Uq9CsLxaxkawgUInr5pQcbw5kC0+KeEZb6RhukCVWrjP8UeuDF63T90XD8G6VnfQlhXIhq+1bTT9nrVXB4ur/k=
