script: bash ./deploy.sh
language: php
php:
- 7.2
env:
  global:
  - GH_REF: github.com/UDOOboard/X86-Docs.git
  - secure: s0DYtyKXYaoGjVP+2wPe7xMjLkisN4dZDleFm4EcW1kbQFMYdHBuKGpk5RFCtjbHVRmhnM+6IgfwGW7A44JJZAz75Ds6+wikK3E9qnwSON3V9ugt7RFimBfHbNUsunPO4j4YdXdX3IvQ+CGqGZyTSsqfTUYIhaoGxeCOgCEpGYW4cpTQVizwrLYDClIajl4uykSl3wZD7w/YGi1RPfYF1uDinP95EEbVG9lIn5Uqctw2ISbWD8xXbuK4KQj4wWp+lNq1KMNyMxpYtc3Q7pyIBY07r41TSiaCyM7j1tQlbrEVcS3MTqs8XLJVAn2gXTcgzAlQwdZxWc3nEBt/hpsM7tlGV3ubnYnApMntCxUyKs/T20NJWlL4P5wmm+6X0Ct/SoqTYuLso5JscZrOwCEN9xTpDEArh+rIVm0v6LDnkgy/O6uvMUi232JQ+NobuzsPkW8SzfFWHTQwjRUgoKDXzcx5e/DJRnRezZsKoQjExh2X4pw5cHudE/hrw86As/umvjVM4f2bA16MSHmQmQ8Ue+H+s9hx/uLP4mltZVokZqgtLThqS4A0s9ICw5jCWHJAHaeYHTGrSjyC6b46UR4o9Y+QZgmBOqI2pOStDRpGHh78xcXZzPyWigew6Y9rVJNRPdWzqmQSNlV1zzTMK2aAXGkuUUu1mAfTX0nkVsFFVi4=
